name: deploy-multi-k8s

on:
  push:
    branches: 
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
